name: Actions to take on pushes to main
on:
  push:
    branches:
    - test-automation
jobs:
  job:
    continue-on-error: true
    name: Assign IDs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.4'
    - run: |
        go get -u github.com/google/osv/vulnfeeds/cmd/ids
        ids -dir=./vulns -prefix PYSEC
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
      env:
        GONOPROXY: github.com/google/osv
    - run: git commit -m 'Assign IDs'
    - run: git push
